import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg.primary },
  screenCentered: { flex: 1, backgroundColor: colors.bg.primary, justifyContent: 'center', alignItems: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', paddingTop: 60, paddingHorizontal: 16, paddingBottom: 16, backgroundColor: colors.bg.surface, borderBottomWidth: 1, borderBottomColor: colors.border.default },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text.primary },
  backButton: { marginRight: 12, padding: 4 },
  messageBubble: { maxWidth: '85%', padding: 12, borderRadius: 12, marginBottom: 12 },
  userBubble: { alignSelf: 'flex-end', backgroundColor: colors.bg.elevated },
  assistantBubble: { alignSelf: 'flex-start', backgroundColor: colors.bg.surface, borderWidth: 1, borderColor: colors.border.default },
  messageText: { color: colors.text.primary, fontSize: 15, lineHeight: 22 },
  timestamp: { fontSize: 11, color: colors.text.muted, marginTop: 8, alignSelf: 'flex-end' },
  inputContainer: { flexDirection: 'row', alignItems: 'flex-end', padding: 12, backgroundColor: colors.bg.surface, borderTopWidth: 1, borderTopColor: colors.border.default },
  textInput: { flex: 1, backgroundColor: colors.bg.elevated, borderRadius: 20, paddingHorizontal: 16, paddingVertical: 10, color: colors.text.primary, fontSize: 16, maxHeight: 100 },
  sendButton: { marginLeft: 8, padding: 10, borderRadius: 20, backgroundColor: colors.bg.elevated },
  sendButtonDisabled: { opacity: 0.5 },
  card: { backgroundColor: colors.bg.surface, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: colors.border.default },
  inputLabel: { fontSize: 14, fontWeight: '600', color: colors.text.secondary, marginBottom: 6, marginTop: 12 },
  formInput: { backgroundColor: colors.bg.elevated, borderRadius: 8, padding: 14, color: colors.text.primary, fontSize: 16 },
  formInputMultiline: { backgroundColor: colors.bg.elevated, borderRadius: 8, padding: 14, color: colors.text.primary, fontSize: 16, minHeight: 80, textAlignVertical: 'top' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: colors.bg.primary, borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: colors.border.default },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: colors.text.primary },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 80, paddingHorizontal: 40 },
  emptyText: { fontSize: 18, color: colors.text.secondary, marginTop: 16 },
  emptySubtext: { fontSize: 14, color: colors.text.muted, marginTop: 8, textAlign: 'center' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.bg.primary },
  loadingText: { color: colors.text.secondary, marginTop: 12, fontSize: 16 },
  primaryButton: { backgroundColor: colors.accent, borderRadius: 8, paddingVertical: 14, paddingHorizontal: 24, alignItems: 'center' },
  primaryButtonText: { color: colors.text.onAccent, fontSize: 16, fontWeight: '600' },
  fab: { position: 'absolute', right: 20, bottom: 20, width: 60, height: 60, borderRadius: 30, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 8 },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.bg.surface, borderRadius: 10, marginHorizontal: 16, marginVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.border.default },
  searchInput: { flex: 1, color: colors.text.primary, fontSize: 16, paddingVertical: 12, marginLeft: 8 },
});
