import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  // ── Layout ────────────────────────────────────────────────────────────
  container: { flex: 1, backgroundColor: colors.bg.primary },
  tabBar: { flexDirection: 'row', backgroundColor: colors.bg.surface, borderBottomWidth: 1, borderBottomColor: colors.border.default },
  tab: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, gap: 6 },
  activeTab: { borderBottomWidth: 2, borderBottomColor: colors.accent },
  tabText: { fontSize: 14, fontWeight: '600', color: colors.text.secondary },
  activeTabText: { color: colors.accent },
  content: { flex: 1 },

  // ── Shared Section ────────────────────────────────────────────────────
  sectionTitle: { fontSize: 22, fontWeight: 'bold', color: colors.text.primary, marginBottom: 4 },
  sectionSubtitle: { fontSize: 14, color: colors.text.muted, marginBottom: 16 },

  // ── Flowcharts ────────────────────────────────────────────────────────
  flowchartList: { padding: 16 },
  flowchartItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.bg.surface, borderRadius: 12, padding: 16, marginBottom: 12 },
  flowchartIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.bg.elevated, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  flowchartInfo: { flex: 1 },
  flowchartName: { fontSize: 16, fontWeight: '600', color: colors.text.primary, marginBottom: 4 },
  flowchartDesc: { fontSize: 13, color: colors.text.muted },
  flowchartActive: { padding: 16 },
  backButton: { flexDirection: 'row', alignItems: 'center', marginBottom: 16, gap: 8 },
  backButtonText: { color: colors.accent, fontSize: 16 },
  flowchartTitle: { fontSize: 24, fontWeight: 'bold', color: colors.text.primary, marginBottom: 4 },
  flowchartSymptom: { fontSize: 14, color: colors.text.muted, marginBottom: 20 },
  nodeCard: { backgroundColor: colors.bg.surface, borderRadius: 16, padding: 20, borderWidth: 1, borderColor: colors.border.default },
  resultHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 8 },
  resultLabel: { fontSize: 18, fontWeight: 'bold', color: colors.status.success },
  resultText: { fontSize: 16, color: colors.text.bright, lineHeight: 24, marginBottom: 12 },
  tipBox: { flexDirection: 'row', backgroundColor: colors.bg.elevated, borderRadius: 8, padding: 12, gap: 8, alignItems: 'flex-start' },
  tipText: { flex: 1, fontSize: 14, color: colors.accent, lineHeight: 20 },
  restartButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accent, borderRadius: 8, padding: 12, marginTop: 16, gap: 8 },
  restartButtonText: { color: colors.text.onAccent, fontSize: 16, fontWeight: '600' },
  questionText: { fontSize: 18, color: colors.text.primary, marginBottom: 20, lineHeight: 26 },
  answerButtons: { flexDirection: 'row', gap: 12 },
  answerButton: { flex: 1, padding: 14, borderRadius: 10, alignItems: 'center' },
  yesButton: { backgroundColor: colors.status.success },
  noButton: { backgroundColor: colors.status.error },
  answerButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },

  // ── Voltages ──────────────────────────────────────────────────────────
  voltageList: { padding: 16 },
  voltageCard: { backgroundColor: colors.bg.surface, borderRadius: 12, marginBottom: 12, overflow: 'hidden' },
  voltageHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  voltageName: { fontSize: 16, fontWeight: 'bold', color: colors.accent },
  voltageFamily: { fontSize: 13, color: colors.text.secondary, marginTop: 2 },
  voltageDesc: { fontSize: 12, color: colors.text.muted, marginTop: 2 },
  voltageTable: { paddingHorizontal: 16, paddingBottom: 16 },
  voltageRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.border.default },
  voltageNode: { flex: 1, fontSize: 14, color: colors.text.bright },
  voltageValue: { fontSize: 14, fontWeight: '600', color: colors.accent, minWidth: 100, textAlign: 'right' },
  voltageNotes: { fontSize: 12, color: colors.text.muted, marginLeft: 8, maxWidth: 100 },

  // ── Calculator ────────────────────────────────────────────────────────
  calculatorContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 16 },
  calcCategoryHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.bg.surface, borderRadius: 12, padding: 16, marginBottom: 8 },
  calcCategoryTitle: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  calcCategoryText: { fontSize: 16, fontWeight: '600', color: colors.text.primary },
  calcCategoryContent: { marginBottom: 12 },
  calcCard: { backgroundColor: colors.bg.surface, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: colors.border.default },
  calcTitle: { fontSize: 16, fontWeight: 'bold', color: colors.accent, marginBottom: 4 },
  calcDesc: { fontSize: 13, color: colors.text.muted, marginBottom: 12 },
  calcInputRow: { flexDirection: 'row', gap: 12 },
  calcInputGroup: { flex: 1, marginBottom: 12 },
  calcLabel: { fontSize: 13, color: colors.text.secondary, marginBottom: 6 },
  calcInput: { backgroundColor: colors.bg.elevated, borderRadius: 8, padding: 12, color: colors.text.primary, fontSize: 15 },
  calcResult: { backgroundColor: colors.bg.elevated, borderRadius: 8, padding: 12, marginTop: 4 },
  calcResultText: { fontSize: 14, color: colors.text.bright, marginBottom: 4 },
  calcResultValue: { fontWeight: 'bold', color: colors.accent },
  tubeTypeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tubeTypeBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.bg.elevated, borderWidth: 1, borderColor: colors.border.default },
  tubeTypeBtnActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  tubeTypeBtnText: { fontSize: 14, color: colors.text.secondary, fontWeight: '500' },
  tubeTypeBtnTextActive: { color: colors.text.onAccent },

  // ── Articles ──────────────────────────────────────────────────────────
  articlesContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 16 },
  articlesHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 },
  importButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.accent, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, gap: 6 },
  importButtonText: { color: colors.text.onAccent, fontSize: 14, fontWeight: '600' },
  loadingContainer: { alignItems: 'center', paddingVertical: 60 },
  loadingText: { color: colors.text.secondary, marginTop: 12, fontSize: 14 },
  emptyContainer: { alignItems: 'center', paddingVertical: 60 },
  emptyTitle: { color: colors.text.bright, fontSize: 20, fontWeight: '600', marginTop: 16, marginBottom: 8 },
  emptySubtitle: { color: colors.text.muted, fontSize: 14, textAlign: 'center', marginBottom: 24 },
  emptyImportButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.bg.surface, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8, gap: 8, borderWidth: 1, borderColor: colors.accent },
  emptyImportText: { color: colors.accent, fontSize: 14, fontWeight: '600' },
  articlesList: { gap: 12 },
  articleCard: { flexDirection: 'row', backgroundColor: colors.bg.surface, borderRadius: 12, padding: 16, alignItems: 'center' },
  articleContent: { flex: 1 },
  articleTitle: { color: colors.text.bright, fontSize: 16, fontWeight: '600', marginBottom: 8 },
  articleMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  circuitBadge: { backgroundColor: colors.bg.elevated, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
  circuitBadgeText: { color: colors.accent, fontSize: 12, fontWeight: '600' },
  articleSource: { color: colors.text.muted, fontSize: 12 },
  deleteButton: { padding: 8 },
  creditSection: { alignItems: 'center', paddingVertical: 24 },
  creditText: { color: colors.text.muted, fontSize: 12 },
  creditLink: { color: colors.accent, textDecorationLine: 'underline' },

  // ── Import Modal ──────────────────────────────────────────────────────
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.7)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: colors.bg.surface, borderRadius: 16, padding: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { color: colors.accent, fontSize: 20, fontWeight: 'bold' },
  modalLabel: { color: colors.text.secondary, fontSize: 14, marginBottom: 8 },
  modalInput: { backgroundColor: colors.bg.elevated, borderRadius: 8, padding: 14, color: colors.text.primary, fontSize: 16, marginBottom: 8 },
  modalHint: { color: colors.text.muted, fontSize: 12, marginBottom: 20 },
  modalButton: { flexDirection: 'row', backgroundColor: colors.accent, borderRadius: 8, padding: 14, alignItems: 'center', justifyContent: 'center', gap: 8 },
  modalButtonDisabled: { opacity: 0.6 },
  modalButtonText: { color: colors.text.onAccent, fontSize: 16, fontWeight: '600' },

  // ── TAVA Podcast ──────────────────────────────────────────────────────
  tavaContainer: { flex: 1, paddingHorizontal: 16 },
  tavaHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingTop: 16, paddingBottom: 12, gap: 12 },
  syncButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.accent, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, gap: 6 },
  syncButtonDisabled: { opacity: 0.7 },
  syncButtonText: { color: colors.text.onAccent, fontSize: 13, fontWeight: '600' },
  podcastSearchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.bg.elevated, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 16, gap: 10 },
  podcastSearchInput: { flex: 1, color: colors.text.primary, fontSize: 16 },
  episodesList: { gap: 16 },
  episodeCard: { backgroundColor: colors.bg.surface, borderRadius: 12, overflow: 'hidden' },
  episodeHeader: { flexDirection: 'row', alignItems: 'center', padding: 14, backgroundColor: colors.bg.elevated, gap: 12 },
  episodeNumberBadge: { backgroundColor: colors.accent, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  episodeNumberText: { color: colors.text.onAccent, fontSize: 12, fontWeight: 'bold' },
  episodeTitleText: { flex: 1, color: colors.text.bright, fontSize: 15, fontWeight: '600' },
  episodeHeaderIcons: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  openLinkButton: { padding: 4 },
  topicsList: { padding: 12, gap: 8 },
  topicItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: colors.border.default },
  topicTimestamp: { color: colors.accent, fontSize: 12, fontFamily: 'monospace', minWidth: 50 },
  topicText: { flex: 1, color: colors.text.bright, fontSize: 14 },
});
